"""
aisence — 전체 파이프라인
1. 무슨 느낌의 음악인지 입력
2. Claude API로 Suno 프롬프트 생성
3. Suno에서 음악 만들고 music_file/ 폴더에 넣기
4. 영상 생성 + 유튜브 업로드
"""

import os
import sys
import anthropic
from make_video import make_video
from upload_youtube import upload_video

GENRE_CHOICES = ["lofi", "heal", "bass", "dawn", "drive",
                 "drive_summer", "drive_night", "drive_hype", "drive_chill", "drive_rain"]

MUSIC_FILE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "music_file")


def generate_suno_prompts(mood: str) -> str:
    """Claude API로 Suno 프롬프트 5가지 생성"""
    client = anthropic.Anthropic()
    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1024,
        messages=[
            {
                "role": "user",
                "content": f"""당신은 Suno AI 음악 생성 전문가입니다.
아래 느낌에 맞는 Suno 프롬프트를 5가지 작성해주세요.

느낌: {mood}

각 프롬프트는 아래 형식으로 작성해주세요:
- 영어로 작성 (Suno는 영어 프롬프트가 더 효과적)
- 장르, 분위기, 악기, BPM 등 구체적으로
- 한 줄로 간결하게

형식:
1. [프롬프트]
2. [프롬프트]
3. [프롬프트]
4. [프롬프트]
5. [프롬프트]"""
            }
        ]
    )
    return response.content[0].text


def list_music_files():
    """music_file 폴더의 파일 목록 출력"""
    if not os.path.exists(MUSIC_FILE_DIR):
        os.makedirs(MUSIC_FILE_DIR)
        return []
    files = os.listdir(MUSIC_FILE_DIR)
    return files


def pick_file(files, ext_filter=None, label="파일"):
    """파일 목록에서 선택"""
    filtered = [f for f in files if ext_filter is None or f.lower().endswith(ext_filter)]
    if not filtered:
        print(f"\n[!] {label} 파일이 없습니다. music_file/ 폴더에 넣어주세요.")
        return None
    print(f"\n{label} 선택:")
    for i, f in enumerate(filtered, 1):
        print(f"  {i}. {f}")
    while True:
        try:
            choice = int(input("번호 입력: "))
            if 1 <= choice <= len(filtered):
                return os.path.join(MUSIC_FILE_DIR, filtered[choice - 1])
        except ValueError:
            pass
        print("올바른 번호를 입력해주세요.")


def main():
    print("=" * 55)
    print("  aisence 전체 파이프라인")
    print("=" * 55)

    # STEP 1: 느낌 입력
    print("\n▶ STEP 1: 음악 느낌 입력")
    mood = input("무슨 느낌의 음악을 원하세요? > ").strip()
    if not mood:
        print("느낌을 입력해주세요.")
        sys.exit(1)

    # STEP 2: Suno 프롬프트 생성
    print("\n▶ STEP 2: Suno 프롬프트 생성 중...")
    prompts = generate_suno_prompts(mood)
    print("\n" + "─" * 55)
    print(prompts)
    print("─" * 55)

    # STEP 3: Suno에서 음악 생성 대기
    print("\n▶ STEP 3: Suno에서 음악 만들기")
    print("  위 프롬프트로 Suno에서 음악을 생성하고")
    print("  mp3 파일과 이미지 파일을 music_file/ 폴더에 넣어주세요.")
    input("\n  완료되면 Enter를 눌러주세요...")

    # STEP 4: 파일 선택
    print("\n▶ STEP 4: 파일 선택")
    files = list_music_files()
    if not files:
        print("music_file/ 폴더가 비어있습니다.")
        sys.exit(1)

    audio_path = pick_file(files, ext_filter=(".mp3", ".wav"), label="오디오")
    if not audio_path:
        sys.exit(1)

    image_path = pick_file(files, ext_filter=(".png", ".jpg", ".jpeg"), label="이미지")
    if not image_path:
        sys.exit(1)

    # STEP 5: 유튜브 정보 입력
    print("\n▶ STEP 5: 유튜브 정보 입력")
    title = input("유튜브 제목: ").strip()
    if not title:
        print("제목을 입력해주세요.")
        sys.exit(1)

    print(f"\n장르 선택: {', '.join(GENRE_CHOICES)}")
    genre = input("장르 입력 (기본: lofi) > ").strip() or "lofi"
    if genre not in GENRE_CHOICES:
        print(f"올바른 장르를 입력해주세요: {GENRE_CHOICES}")
        sys.exit(1)

    suno_credit = "\n\n🎵 Music generated by Suno AI"
    description = input("추가 설명 (없으면 Enter): ").strip()
    if description:
        description = description + suno_credit
    else:
        description = None  # upload_youtube.py의 기본 설명 + Suno 크레딧은 별도 처리

    # STEP 6: 영상 생성
    print("\n▶ STEP 6: 영상 생성")
    output_path = make_video(image_path, audio_path)

    # STEP 7: 유튜브 업로드
    print("\n▶ STEP 7: 유튜브 업로드")

    # Suno 출처를 기본 설명에 추가
    from upload_youtube import GENRE_DESC
    final_desc = (description or GENRE_DESC.get(genre, GENRE_DESC["lofi"])) + suno_credit

    video_id = upload_video(output_path, title, genre, description=final_desc)

    print("\n" + "=" * 55)
    print("  전체 완료!")
    print(f"  영상: {output_path}")
    print(f"  유튜브: https://www.youtube.com/watch?v={video_id}")
    print("=" * 55)


if __name__ == "__main__":
    main()
